authentication/urls.py
from django.conf.urls import url
from . import views

app_name = 'authen'

urlpatterns = [
    # url(r'^$', views.authentication),
    # url(r'^verify$', views.verify_account, name='verify_account'),
    url(r'^login$', views.Login.as_view(), name='authenticate'),
    url(r'^logout$', views.Logout.as_view(), name='authenticate'),
    url(r'^sign_up$', views.SignUp.as_view(), name='sign_up'),
    url(r'^user', views.UserInfo.as_view(), name='user_info'),
    url(r'^check_permission$', views.CheckPermission.as_view(), name='check_permisson'),
    # url(r'^test_permission$', views.test_permission),
]

kabkao/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^authen/', include('authentication.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

authentication/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProxy(User):

    class Meta:
        proxy = True
        permissions = (
            ('view_user', 'View user'),
        )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField()


class CustomPermission(models.Model):

    class Meta:
        managed = False
        permissions = (
            ('add_menu', 'Can add menu'),
            ('view_menu', 'Can view menu'),
            ('change_menu', 'Can change menu'),
            ('delete_menu', 'Can delete menu'),
            ('add_order', 'Can add order'),
            ('view_order', 'Can view order'),
            ('change_order', 'Can change order'),
            ('delete_order', 'Can delete order'),
        )

authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.shortcuts import render
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from authentication.models import CustomPermission, Profile
from authentication.serializer import FullAccountSerializer, BasicAccountSerializer
from guardian.shortcuts import assign_perm
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


import ErrorCode
import ResponseFormat


class SignUp(APIView):

    @staticmethod
    def get(request):
        return render(request, 'sign_up.html')

    def post(self, request):
        user = None
        try:
            if not request.user.is_anonymous():
                return Response(ResponseFormat.error(ErrorCode.REQUIRE_ANONYMOUS, "Cannot sign up while staying logged in."))
            if User.objects.filter(email=request.data['email']).exists():
                raise Exception
            group = PermissionManagement().get_standard_user_group()
            data = request.data
            user = User.objects.create_user(username=data['username'], email=data['email'], password=data['password'], first_name=data['first_name'], last_name=data['last_name'])
            user.groups.add(group)
            Profile.objects.create(user=user, address=data['address'])
            self.setExtraPermissions(user)
            Token.objects.create(user=user)
            return Response({'success': True,
                         'payload': {
                             'token': Token.objects.get(user=user).key,
                             'user_data': FullAccountSerializer(user).data
                         }})
        except Exception as ex:
            if user and not user.is_anonymous:
                user.delete()
            return Response(ResponseFormat.error(ErrorCode.USERNAME_OR_EMAIL_ALREADY_EXISTS, "Username and email may already exist, or there are incomplete required fields. Please use another one or try to fill out the form again."), status=status.HTTP_406_NOT_ACCEPTABLE)

    def setExtraPermissions(self, user):
        assign_perm('change_user', user, user)
        assign_perm('delete_user', user, user)


class Login(APIView):

    @staticmethod
    def get(request):
        return render(request, 'login.html')

    @staticmethod
    def post(request):
        user = authenticate(username=request.data['username'], password=request.data['password'])
        if user:
            # login(request, user)
            return Response(ResponseFormat.success({
                                 'token': Token.objects.get(user=user).key,
                                 'user_data': FullAccountSerializer(user).data
                             }))
        return Response(ResponseFormat.error(ErrorCode.USERNAME_OR_PASSWORD_INCORRECT, "Username or password is incorrect. Please try again."), status=status.HTTP_404_NOT_FOUND)


class Logout(APIView):

    @staticmethod
    def get(request):
        try:
            logout(request)
            return Response(ResponseFormat.success())
        except Exception:
            return Response(ResponseFormat.error(ErrorCode.INTERNAL_SERVER_ERROR, "Logout failed."), status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class UserInfo(APIView):

    permission_classes = (IsAuthenticated, )

    def get(self, request):
        try:
            user_obj = User.objects.get(pk=request.query_params['id'])
            user_data = self.get_serializer_class(user_obj)(user_obj).data
            return Response(ResponseFormat.success({'user_data': user_data}))
        except Exception:
            return Response(ResponseFormat.error(ErrorCode.DATA_NOT_FOUND, "User data not found."), status=status.HTTP_404_NOT_FOUND)

    @staticmethod
    def put(request):
        try:
            user = User.objects.get(pk=request.data['id'])
            if request.user.has_perm('change_user', user):
                serializer = FullAccountSerializer(user, data=request.data, partial=True)
                if serializer.is_valid():
                    user = serializer.save()
                    return Response(ResponseFormat.success({"user_data": FullAccountSerializer(user).data}))
                return Response(ResponseFormat.error(ErrorCode.INPUT_DATA_INVALID, "Input data is invalid. Please correct and try again.", status.HTTP_406_NOT_ACCEPTABLE))
            return Response(ResponseFormat.error(ErrorCode.FORBIDDEN, "Permission not allowed."))
        except Exception:
            return Response(ResponseFormat.error(ErrorCode.DATA_NOT_FOUND, "User data not found."))

    @staticmethod
    def delete(request):
        try:
            user = User.objects.get(pk=request.data['id'])
            if request.user.has_perm('delete_user', user):
                user.delete()
                return Response(ResponseFormat.success())
            return Response(ResponseFormat.error(ErrorCode.FORBIDDEN, "Permission not allowed."), status=status.HTTP_403_FORBIDDEN)
        except Exception:
            return Response(ResponseFormat.error(ErrorCode.INTERNAL_SERVER_ERROR, "Delete failed."))

    def get_serializer_class(self, user_obj):
        user = self.request.user
        if user.has_perm('change_user', user_obj):
            return FullAccountSerializer
        return BasicAccountSerializer


# def test_permission(request):
#         if not request.user.is_staff():
#     # PermissionManagement().update_standard_user_group_permission()
#     user = User.objects.get(pk=7)
#     # perm_shortcut = Permission.objects.get
#     # content_type = ContentType.objects.get_for_model(User)
#     # user.user_permissions.set([perm_shortcut(content_type=content_type, codename='view_user'),])
#     # user2 = User.objects.get(pk=5)
#     # assign_perm('view_user', user, user2)
#     print user.has_perm('delete_user', user)
#     # return Response(user.has_perm('add_user'))
#     return HttpResponse('success')


class CheckPermission(APIView):
    permission_classes = (IsAuthenticated, )

    @staticmethod
    def get(request):
        try:
            user = request.user
            permission = request.query_params['permission']
            if user.has_perm(permission, user) or user.has_perm('authentication.' + permission):
                return Response(ResponseFormat.success({'is_allowed': True}))
            return Response(ResponseFormat.success({'is_allowed': False}))
        except Exception:
            return Response(ResponseFormat.error(ErrorCode.INTERNAL_SERVER_ERROR, "Permission checking failed."))


class PermissionManagement():

    def get_standard_user_group(self):
        group = Group.objects.get_or_create(name='standard_users')
        return group[0]

    def update_standard_user_group_permission(self):
        content_type = ContentType.objects.get_for_model(User)
        perm_shortcut = Permission.objects.get
        user_permissions = [perm_shortcut(content_type=content_type, codename='view_user'),]

        content_type = ContentType.objects.get_for_model(CustomPermission)
        menu_permissions = [perm_shortcut(content_type=content_type, codename='view_menu'),]
        order_permissions = [perm_shortcut(content_type=content_type, codename='add_order'),
                             perm_shortcut(content_type=content_type, codename='view_order'),
                             perm_shortcut(content_type=content_type, codename='delete_order'),]
        group = self.get_standard_user_group()
        group.permissions.set(user_permissions + menu_permissions + order_permissions)
        group.save()

authentication/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/main.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block css %} {% endblock %}
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>
<script>{% block script %}{% endblock %}</script>

authentication/templates/login.html
{% extends "base_generic.html" %}
{% block title %}Kabkao Online{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-offset4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><h3>Kabkao Login</h3></div>
                <div class="panel-body">
                    <form method="post" action="{% url 'authen:authenticate' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-3"><label for="username">Username</label></div>
                            <div class="col-md-9"><input type="text" class="form-control" id="username" name="username"></div>
                        </div>
                        <br><br>
                        <div class="form-group">
                            <div class="col-md-3"><label for="password">Password</label></div>
                            <div class="col-md-9"><input type="password" class="form-control" id="password" name="password"></div>
                        </div>
                        <br><br>
                        <div class="form-group"><button class="btn btn-primary pull-right">Submit</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
{% endblock %}

authentication/templates/sign_up.html
{% extends "base_generic.html" %}
{% block title %}Kabkao Online{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-offset3 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><h3>Sign up</h3></div>
                <div class="panel-body">
                    <form method="post" action="{% url 'authen:sign_up' %}" name="sign_up">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-4"><label for="email">Username</label></div>
                            <div class="col-md-8"><input type="text" class="form-control" id="username" name="username"></div>
                        </div>
                        <br><br>
                        <div class="form-group">
                            <div class="col-md-4"><label for="email">Email</label></div>
                            <div class="col-md-8"><input type="email" class="form-control" id="email" name="email"></div>
                        </div>
                        <br><br>
                        <div class="form-group">
                            <div class="col-md-4"><label for="password">Password</label></div>
                            <div class="col-md-8"><input type="password" class="form-control" id="password" name="password"></div>
                        </div>
                        <br><br>
                        <div class="form-group">
                            <div class="col-md-4"><label for="confirm_password">Confirm Password</label></div>
                            <div class="col-md-8"><input type="password" class="form-control" id="confirm_password" name="confirm_password"></div>
                        </div>
                        <br><br>
                        <div class="form-group" onclick="checkPassword(event)"><button class="btn btn-primary pull-right">Submit</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-sm" id="warning-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Password mismatch!!</h4>
                </div>
                <div class="modal-body">
                    Your password and confirm password are mismatch. Please try again.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    function checkPassword(event) {
        event.preventDefault();
        if($('#password').val() != $('#confirm_password').val())
            $('#warning-modal').modal('show')
        else {
            document.forms['sign_up'].submit();
        }
    }
{% endblock %}